"""UI strings for the v2 widget, in the 12 site locales — ``_meta["finerx/labels"]``.

The widget (``widget-src/src/labels.ts``) carries the ENGLISH set as a built-in
fallback; the server sends the reader's language with every result, so a
Spanish card never shows an English button. Keys = contract C2 minimum + the
widget-only keys W1 added (``bin`` … ``priceAt``). Placeholders are ``{name}``
and are filled by the widget: ``nearLabel {place}``, ``observed {date}``,
``miles {n}``, ``moreChains {n}``, ``showMore {n}``, ``priceAt {price}
{withCard} {name}``.

The translations are translations of the English — no new promises. The card
law itself is NOT here: it arrives from the API (``card.law``/``card.fine``,
owner-approved text in every locale) and is drawn verbatim. The English set is
held to the card-law word bans by ``tests/test_card_law.py``.
"""
from __future__ import annotations

import functools
import re

EN: dict[str, str] = {
    # --- contract C2 keys ---------------------------------------------------
    "pricesTitle": "Price with the FineRx card, low to high",
    "nearLabel": "Near {place}",
    "approx": "(approximate)",
    "changeZip": "change ZIP",
    "zipPlaceholder": "ZIP code",
    "withCard": "with card",
    "observed": "observed {date}",
    "miles": "{n} mi",
    "moreChains": "+ {n} more chains",
    "allPharmacies": "All pharmacies",
    "showAtCounter": "Show at the counter",
    "save": "Save",
    "print": "Print",
    "email": "Email",
    "sms": "Text message",
    "copy": "Copy",
    "copied": "Copied",
    "noPrice": (
        "We haven't seen a card price for this package yet. Estimated prices are on "
        "our site; show the card at the pharmacy to get the final price."
    ),
    "otherQuantities": "Card prices we have seen for other quantities:",
    "needsZip": "Enter a ZIP code to see pharmacies near you. These are card prices by chain.",
    "notInsurance": "Not insurance",
    "cardTitle": "Prescription Discount Card",
    "cardSub": "Free · no signup · show it to your pharmacist",
    "howToTitle": "At the pharmacy counter",
    "step1": "Show the card, or read out BIN, PCN and Group.",
    "step2": "Ask them to run it as a discount card, not as insurance.",
    "step3": "Ask the price with the card and without it, and pay the lower one.",
    "moreChainOne": "+ 1 more chain",
    "loading": "Loading prices…",
    "error": "Prices didn't load. The card still works.",
    "storeInStore": "pharmacy in store (not verified)",
    "noStock": "We don't see stock — call the pharmacy before you go.",
    # --- widget-only keys ----------------------------------------------------
    "bin": "BIN",
    "pcn": "PCN",
    "group": "Group",
    "zipGo": "OK",
    "zipInvalid": "Enter a 5-digit ZIP code",
    "other": "Other",
    "wallet": "Wallet (printable card)",
    "emailPlaceholder": "Your email",
    "emailSend": "Send card",
    "emailConsent": (
        "We’ll send one email with your card. We don’t store your address and won’t "
        "email you again."
    ),
    "sending": "Sending…",
    "emailSent": "Sent — check your inbox",
    "emailError": "Couldn't send — try again",
    "actionError": "That didn't load. Try again.",
    "directions": "Directions",
    "allFamilies": "All",
    "pharmaciesTitle": "Pharmacies nearby",
    "pricesWithoutStores": "Card price, no store nearby:",
    "showMore": "Show {n} more",
    "close": "Close",
    "noPriceShort": "no card price seen",
    "priceAt": "{price} {withCard} at {name}",
}

_T: dict[str, dict[str, str]] = {
    "es": {
        "pricesTitle": "Precio con la tarjeta FineRx, de menor a mayor",
        "nearLabel": "Cerca de {place}",
        "approx": "(aproximado)",
        "changeZip": "cambiar código postal",
        "zipPlaceholder": "Código postal",
        "withCard": "con tarjeta",
        "observed": "observado el {date}",
        "miles": "{n} mi",
        "moreChains": "+ {n} cadenas más",
        "allPharmacies": "Todas las farmacias",
        "showAtCounter": "Mostrar en el mostrador",
        "save": "Guardar",
        "print": "Imprimir",
        "email": "Correo electrónico",
        "sms": "Mensaje de texto",
        "copy": "Copiar",
        "copied": "Copiado",
        "noPrice": (
            "Aún no hemos visto un precio con tarjeta para este paquete. Los precios "
            "estimados están en nuestro sitio; muestre la tarjeta en la farmacia para "
            "obtener el precio final."
        ),
        "otherQuantities": "Precios con tarjeta que hemos visto para otras cantidades:",
        "needsZip": (
            "Ingrese un código postal para ver farmacias cerca de usted. Estos son "
            "precios con tarjeta por cadena."
        ),
        "notInsurance": "No es un seguro",
        "cardTitle": "Tarjeta de descuento para recetas",
        "cardSub": "Gratis · sin registro · muéstrela en la farmacia",
        "howToTitle": "En el mostrador de la farmacia",
        "step1": "Muestre la tarjeta o dicte BIN, PCN y Group.",
        "step2": "Pida que la procesen como tarjeta de descuento, no como seguro.",
        "step3": "Pregunte el precio con la tarjeta y sin ella, y pague el menor.",
        "moreChainOne": "+ 1 cadena más",
        "loading": "Cargando precios…",
        "error": "Los precios no se cargaron. La tarjeta sigue funcionando.",
        "storeInStore": "farmacia dentro de la tienda (sin verificar)",
        "noStock": "No vemos el inventario: llame a la farmacia antes de ir.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Grupo",
        "zipGo": "OK",
        "zipInvalid": "Ingrese un código postal de 5 dígitos",
        "other": "Otra",
        "wallet": "Billetera (tarjeta imprimible)",
        "emailPlaceholder": "Su correo electrónico",
        "emailSend": "Enviar tarjeta",
        "emailConsent": (
            "Le enviaremos un solo correo con su tarjeta. No guardamos su dirección "
            "ni le volveremos a escribir."
        ),
        "sending": "Enviando…",
        "emailSent": "Enviado: revise su bandeja de entrada",
        "emailError": "No se pudo enviar; inténtelo de nuevo",
        "actionError": "No se pudo cargar. Inténtelo de nuevo.",
        "directions": "Cómo llegar",
        "allFamilies": "Todas",
        "pharmaciesTitle": "Farmacias cercanas",
        "pricesWithoutStores": "Precio con tarjeta, sin tienda cercana:",
        "showMore": "Mostrar {n} más",
        "close": "Cerrar",
        "noPriceShort": "sin precio con tarjeta",
        "priceAt": "{price} {withCard} en {name}",
    },
    "zh": {
        "pricesTitle": "使用 FineRx 卡的价格，从低到高",
        "nearLabel": "{place} 附近",
        "approx": "（大致位置）",
        "changeZip": "更改邮编",
        "zipPlaceholder": "邮政编码",
        "withCard": "用卡",
        "observed": "观察于 {date}",
        "miles": "{n} 英里",
        "moreChains": "+ 另外 {n} 家连锁",
        "allPharmacies": "所有药房",
        "showAtCounter": "在柜台出示",
        "save": "保存",
        "print": "打印",
        "email": "电子邮件",
        "sms": "短信",
        "copy": "复制",
        "copied": "已复制",
        "noPrice": "我们尚未见到此包装的用卡价格。估计价格请见我们的网站；在药房出示此卡即可获得最终价格。",
        "otherQuantities": "我们见到的其他数量的用卡价格：",
        "needsZip": "输入邮政编码即可查看附近的药房。以下为各连锁药房的用卡价格。",
        "notInsurance": "非保险",
        "cardTitle": "处方药折扣卡",
        "cardSub": "免费 · 无需注册 · 出示给药剂师",
        "howToTitle": "在药房柜台",
        "step1": "出示卡片，或报出 BIN、PCN 和 Group。",
        "step2": "请药剂师按折扣卡处理，而不是按保险。",
        "step3": "询问用卡和不用卡的价格，支付较低的那个。",
        "moreChainOne": "+ 另外 1 家连锁",
        "loading": "正在加载价格…",
        "error": "价格未能加载。此卡依然可用。",
        "storeInStore": "店内药房（未核实）",
        "noStock": "我们看不到库存——出发前请先致电药房。",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "组号",
        "zipGo": "确定",
        "zipInvalid": "请输入 5 位邮政编码",
        "other": "其他",
        "wallet": "钱包（可打印的卡）",
        "emailPlaceholder": "您的电子邮件",
        "emailSend": "发送卡",
        "emailConsent": "我们只会发送一封附有您的卡的邮件。我们不会保存您的地址，也不会再给您发邮件。",
        "sending": "正在发送…",
        "emailSent": "已发送——请查看收件箱",
        "emailError": "发送失败——请重试",
        "actionError": "未能加载。请重试。",
        "directions": "路线",
        "allFamilies": "全部",
        "pharmaciesTitle": "附近的药房",
        "pricesWithoutStores": "有用卡价格，但附近没有门店：",
        "showMore": "再显示 {n} 个",
        "close": "关闭",
        "noPriceShort": "未见用卡价格",
        "priceAt": "{name}：{price}（{withCard}）",
    },
    "vi": {
        "pricesTitle": "Giá với thẻ FineRx, từ thấp đến cao",
        "nearLabel": "Gần {place}",
        "approx": "(ước tính)",
        "changeZip": "đổi mã ZIP",
        "zipPlaceholder": "Mã ZIP",
        "withCard": "với thẻ",
        "observed": "ghi nhận ngày {date}",
        "miles": "{n} dặm",
        "moreChains": "+ {n} chuỗi khác",
        "allPharmacies": "Tất cả nhà thuốc",
        "showAtCounter": "Xuất trình tại quầy",
        "save": "Lưu",
        "print": "In",
        "email": "Email",
        "sms": "Tin nhắn",
        "copy": "Sao chép",
        "copied": "Đã sao chép",
        "noPrice": (
            "Chúng tôi chưa thấy giá với thẻ cho gói này. Giá ước tính có trên trang "
            "của chúng tôi; hãy xuất trình thẻ tại nhà thuốc để biết giá cuối cùng."
        ),
        "otherQuantities": "Giá với thẻ chúng tôi đã thấy cho số lượng khác:",
        "needsZip": "Nhập mã ZIP để xem các nhà thuốc gần bạn. Đây là giá với thẻ theo chuỗi.",
        "notInsurance": "Không phải bảo hiểm",
        "cardTitle": "Thẻ giảm giá thuốc theo toa",
        "cardSub": "Miễn phí · không cần đăng ký · đưa cho dược sĩ",
        "howToTitle": "Tại quầy nhà thuốc",
        "step1": "Đưa thẻ hoặc đọc mã BIN, PCN và Group.",
        "step2": "Đề nghị xử lý như thẻ giảm giá, không phải bảo hiểm.",
        "step3": "Hỏi giá có thẻ và không có thẻ, rồi trả mức thấp hơn.",
        "moreChainOne": "+ 1 chuỗi nữa",
        "loading": "Đang tải giá…",
        "error": "Không tải được giá. Thẻ vẫn dùng được.",
        "storeInStore": "nhà thuốc trong cửa hàng (chưa xác minh)",
        "noStock": "Chúng tôi không thấy hàng tồn — hãy gọi nhà thuốc trước khi đến.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Nhóm",
        "zipGo": "OK",
        "zipInvalid": "Nhập mã ZIP gồm 5 chữ số",
        "other": "Khác",
        "wallet": "Ví (thẻ để in)",
        "emailPlaceholder": "Email của bạn",
        "emailSend": "Gửi thẻ",
        "emailConsent": (
            "Chúng tôi sẽ gửi một email kèm thẻ của bạn. Chúng tôi không lưu địa chỉ "
            "và sẽ không gửi thêm email."
        ),
        "sending": "Đang gửi…",
        "emailSent": "Đã gửi — hãy kiểm tra hộp thư",
        "emailError": "Không gửi được — hãy thử lại",
        "actionError": "Không tải được. Hãy thử lại.",
        "directions": "Chỉ đường",
        "allFamilies": "Tất cả",
        "pharmaciesTitle": "Nhà thuốc gần đây",
        "pricesWithoutStores": "Có giá với thẻ, không có cửa hàng gần:",
        "showMore": "Xem thêm {n}",
        "close": "Đóng",
        "noPriceShort": "chưa thấy giá với thẻ",
        "priceAt": "{price} {withCard} tại {name}",
    },
    "tl": {
        "pricesTitle": "Presyo gamit ang FineRx card, mula mababa hanggang mataas",
        "nearLabel": "Malapit sa {place}",
        "approx": "(tinatayang lokasyon)",
        "changeZip": "palitan ang ZIP",
        "zipPlaceholder": "ZIP code",
        "withCard": "gamit ang card",
        "observed": "naobserbahan noong {date}",
        "miles": "{n} mi",
        "moreChains": "+ {n} pang chain",
        "allPharmacies": "Lahat ng botika",
        "showAtCounter": "Ipakita sa counter",
        "save": "I-save",
        "print": "I-print",
        "email": "Email",
        "sms": "Text message",
        "copy": "Kopyahin",
        "copied": "Nakopya",
        "noPrice": (
            "Wala pa kaming nakitang presyo gamit ang card para sa package na ito. Nasa "
            "aming site ang mga tinatayang presyo; ipakita ang card sa botika para "
            "makuha ang huling presyo."
        ),
        "otherQuantities": "Mga presyo gamit ang card na nakita namin para sa ibang dami:",
        "needsZip": (
            "Maglagay ng ZIP code para makita ang mga botika malapit sa iyo. Ito ang mga "
            "presyo gamit ang card ayon sa chain."
        ),
        "notInsurance": "Hindi insurance",
        "cardTitle": "Discount Card para sa Reseta",
        "cardSub": "Libre · walang pag-sign up · ipakita sa parmasyutiko",
        "howToTitle": "Sa counter ng parmasya",
        "step1": "Ipakita ang card o basahin ang BIN, PCN at Group.",
        "step2": "Hilingin na gamitin ito bilang discount card, hindi insurance.",
        "step3": "Itanong ang presyo na may card at wala, at bayaran ang mas mababa.",
        "moreChainOne": "+ 1 pang chain",
        "loading": "Nilo-load ang mga presyo…",
        "error": "Hindi na-load ang mga presyo. Gumagana pa rin ang card.",
        "storeInStore": "botika sa loob ng tindahan (hindi pa beripikado)",
        "noStock": "Hindi namin nakikita ang stock — tumawag muna sa botika bago pumunta.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Group",
        "zipGo": "OK",
        "zipInvalid": "Maglagay ng 5-digit na ZIP code",
        "other": "Iba pa",
        "wallet": "Wallet (card na mapi-print)",
        "emailPlaceholder": "Iyong email",
        "emailSend": "Ipadala ang card",
        "emailConsent": (
            "Magpapadala kami ng isang email na may card mo. Hindi namin itinatago ang "
            "address mo at hindi ka na namin iimeilin ulit."
        ),
        "sending": "Ipinapadala…",
        "emailSent": "Naipadala — tingnan ang inbox mo",
        "emailError": "Hindi naipadala — subukan ulit",
        "actionError": "Hindi na-load. Subukan ulit.",
        "directions": "Direksyon",
        "allFamilies": "Lahat",
        "pharmaciesTitle": "Mga botika sa malapit",
        "pricesWithoutStores": "May presyo gamit ang card, walang tindahan sa malapit:",
        "showMore": "Ipakita ang {n} pa",
        "close": "Isara",
        "noPriceShort": "walang nakitang presyo gamit ang card",
        "priceAt": "{price} {withCard} sa {name}",
    },
    "ar": {
        "pricesTitle": "السعر ببطاقة FineRx، من الأقل إلى الأعلى",
        "nearLabel": "بالقرب من {place}",
        "approx": "(تقريبي)",
        "changeZip": "تغيير الرمز البريدي",
        "zipPlaceholder": "الرمز البريدي",
        "withCard": "بالبطاقة",
        "observed": "تمت ملاحظته في {date}",
        "miles": "{n} ميل",
        "moreChains": "+ {n} سلاسل أخرى",
        "allPharmacies": "كل الصيدليات",
        "showAtCounter": "اعرض البطاقة عند الشباك",
        "save": "حفظ",
        "print": "طباعة",
        "email": "البريد الإلكتروني",
        "sms": "رسالة نصية",
        "copy": "نسخ",
        "copied": "تم النسخ",
        "noPrice": (
            "لم نرَ بعد سعرًا بالبطاقة لهذه العبوة. الأسعار التقديرية على موقعنا؛ أظهر "
            "البطاقة في الصيدلية لمعرفة السعر النهائي."
        ),
        "otherQuantities": "أسعار بالبطاقة رأيناها لكميات أخرى:",
        "needsZip": "أدخل الرمز البريدي لرؤية الصيدليات القريبة منك. هذه أسعار بالبطاقة حسب السلسلة.",
        "notInsurance": "ليست تأمينًا",
        "cardTitle": "بطاقة خصم الوصفات الطبية",
        "cardSub": "مجانية · بدون تسجيل · اعرضها على الصيدلي",
        "howToTitle": "عند شباك الصيدلية",
        "step1": "اعرض البطاقة أو اقرأ BIN وPCN وGroup.",
        "step2": "اطلب معالجتها كبطاقة خصم وليس كتأمين.",
        "step3": "اسأل عن السعر مع البطاقة وبدونها وادفع الأقل.",
        "moreChainOne": "+ سلسلة واحدة أخرى",
        "loading": "جارٍ تحميل الأسعار…",
        "error": "لم يتم تحميل الأسعار. البطاقة ما زالت تعمل.",
        "storeInStore": "صيدلية داخل متجر (لم يتم التحقق)",
        "noStock": "لا نرى المخزون — اتصل بالصيدلية قبل الذهاب.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "المجموعة",
        "zipGo": "موافق",
        "zipInvalid": "أدخل رمزًا بريديًا من 5 أرقام",
        "other": "أخرى",
        "wallet": "المحفظة (بطاقة للطباعة)",
        "emailPlaceholder": "بريدك الإلكتروني",
        "emailSend": "إرسال البطاقة",
        "emailConsent": "سنرسل رسالة واحدة تحتوي على بطاقتك. لا نحفظ عنوانك ولن نراسلك مرة أخرى.",
        "sending": "جارٍ الإرسال…",
        "emailSent": "تم الإرسال — تحقق من بريدك الوارد",
        "emailError": "تعذّر الإرسال — حاول مرة أخرى",
        "actionError": "لم يتم التحميل. حاول مرة أخرى.",
        "directions": "الاتجاهات",
        "allFamilies": "الكل",
        "pharmaciesTitle": "صيدليات قريبة",
        "pricesWithoutStores": "سعر بالبطاقة، ولا يوجد متجر قريب:",
        "showMore": "عرض {n} أخرى",
        "close": "إغلاق",
        "noPriceShort": "لم نرَ سعرًا بالبطاقة",
        "priceAt": "{price} {withCard} في {name}",
    },
    "ko": {
        "pricesTitle": "FineRx 카드 적용 가격, 낮은 순",
        "nearLabel": "{place} 근처",
        "approx": "(대략적인 위치)",
        "changeZip": "ZIP 변경",
        "zipPlaceholder": "ZIP 코드",
        "withCard": "카드 적용",
        "observed": "{date} 확인",
        "miles": "{n}마일",
        "moreChains": "+ 체인 {n}곳 더",
        "allPharmacies": "모든 약국",
        "showAtCounter": "카운터에서 보여주기",
        "save": "저장",
        "print": "인쇄",
        "email": "이메일",
        "sms": "문자 메시지",
        "copy": "복사",
        "copied": "복사됨",
        "noPrice": (
            "이 포장에 대한 카드 적용 가격을 아직 확인하지 못했습니다. 예상 가격은 웹사이트에서 "
            "확인하세요. 약국에서 카드를 제시하면 최종 가격을 알 수 있습니다."
        ),
        "otherQuantities": "다른 수량에 대해 확인된 카드 적용 가격:",
        "needsZip": "근처 약국을 보려면 ZIP 코드를 입력하세요. 체인별 카드 적용 가격입니다.",
        "notInsurance": "보험이 아님",
        "cardTitle": "처방약 할인 카드",
        "cardSub": "무료 · 가입 불필요 · 약사에게 보여주세요",
        "howToTitle": "약국 카운터에서",
        "step1": "카드를 보여주거나 BIN, PCN, Group을 불러 주세요.",
        "step2": "보험이 아닌 할인 카드로 처리해 달라고 요청하세요.",
        "step3": "카드 사용 시와 미사용 시 가격을 묻고 더 낮은 금액을 내세요.",
        "moreChainOne": "+ 체인 1곳 더",
        "loading": "가격을 불러오는 중…",
        "error": "가격을 불러오지 못했습니다. 카드는 그대로 사용할 수 있습니다.",
        "storeInStore": "매장 내 약국(확인되지 않음)",
        "noStock": "재고는 확인할 수 없습니다 — 방문 전에 약국에 전화하세요.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "그룹",
        "zipGo": "확인",
        "zipInvalid": "5자리 ZIP 코드를 입력하세요",
        "other": "기타",
        "wallet": "지갑(인쇄용 카드)",
        "emailPlaceholder": "이메일 주소",
        "emailSend": "카드 보내기",
        "emailConsent": "카드가 담긴 이메일을 한 번만 보냅니다. 주소는 저장하지 않으며 다시 이메일을 보내지 않습니다.",
        "sending": "보내는 중…",
        "emailSent": "전송됨 — 받은편지함을 확인하세요",
        "emailError": "보내지 못했습니다 — 다시 시도하세요",
        "actionError": "불러오지 못했습니다. 다시 시도하세요.",
        "directions": "길찾기",
        "allFamilies": "전체",
        "pharmaciesTitle": "근처 약국",
        "pricesWithoutStores": "카드 적용 가격은 있지만 근처 매장이 없음:",
        "showMore": "{n}개 더 보기",
        "close": "닫기",
        "noPriceShort": "카드 적용 가격 없음",
        "priceAt": "{name}: {price} ({withCard})",
    },
    "ru": {
        "pricesTitle": "Цена с картой FineRx, по возрастанию",
        "nearLabel": "Рядом с {place}",
        "approx": "(примерно)",
        "changeZip": "изменить ZIP",
        "zipPlaceholder": "ZIP-код",
        "withCard": "с картой",
        "observed": "по наблюдению на {date}",
        "miles": "{n} миль",
        "moreChains": "+ ещё {n} сетей",
        "allPharmacies": "Все аптеки",
        "showAtCounter": "Показать у кассы",
        "save": "Сохранить",
        "print": "Печать",
        "email": "Эл. почта",
        "sms": "SMS",
        "copy": "Копировать",
        "copied": "Скопировано",
        "noPrice": (
            "Цену по карте для этой упаковки мы ещё не видели. Примерные цены — на "
            "сайте; покажите карту в аптеке — там назовут финальную цену."
        ),
        "otherQuantities": "Цены по карте, которые мы видели для другого количества:",
        "needsZip": "Введите ZIP-код, чтобы увидеть аптеки рядом. Это цены по карте по сетям.",
        "notInsurance": "Не страховка",
        "cardTitle": "Дисконтная карта на рецептурные лекарства",
        "cardSub": "Бесплатно · без регистрации · покажите фармацевту",
        "howToTitle": "У кассы аптеки",
        "step1": "Покажите карту или назовите BIN, PCN и Group.",
        "step2": "Попросите провести её как дисконтную карту, а не как страховку.",
        "step3": "Спросите цену с картой и без неё и заплатите меньшую.",
        "moreChainOne": "+ ещё 1 сеть",
        "loading": "Загружаем цены…",
        "error": "Цены не загрузились. Карта работает и без нас.",
        "storeInStore": "аптека в магазине (не проверено)",
        "noStock": "Наличие мы не видим — позвоните в аптеку перед поездкой.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Группа",
        "zipGo": "OK",
        "zipInvalid": "Введите ZIP-код из 5 цифр",
        "other": "Другое",
        "wallet": "Кошелёк (карта для печати)",
        "emailPlaceholder": "Ваш e-mail",
        "emailSend": "Отправить карту",
        "emailConsent": (
            "Мы отправим одно письмо с картой. Мы не храним ваш адрес и больше не "
            "будем вам писать."
        ),
        "sending": "Отправляем…",
        "emailSent": "Отправлено — проверьте почту",
        "emailError": "Не удалось отправить — попробуйте ещё раз",
        "actionError": "Не загрузилось. Попробуйте ещё раз.",
        "directions": "Маршрут",
        "allFamilies": "Все",
        "pharmaciesTitle": "Аптеки рядом",
        "pricesWithoutStores": "Цена по карте, точек рядом нет:",
        "showMore": "Показать ещё {n}",
        "close": "Закрыть",
        "noPriceShort": "цену по карте не видели",
        "priceAt": "{price} {withCard} в {name}",
    },
    "pt": {
        "pricesTitle": "Preço com o cartão FineRx, do menor para o maior",
        "nearLabel": "Perto de {place}",
        "approx": "(aproximado)",
        "changeZip": "alterar código ZIP",
        "zipPlaceholder": "Código ZIP",
        "withCard": "com cartão",
        "observed": "observado em {date}",
        "miles": "{n} mi",
        "moreChains": "+ {n} outras redes",
        "allPharmacies": "Todas as farmácias",
        "showAtCounter": "Mostrar no balcão",
        "save": "Salvar",
        "print": "Imprimir",
        "email": "E-mail",
        "sms": "Mensagem de texto",
        "copy": "Copiar",
        "copied": "Copiado",
        "noPrice": (
            "Ainda não vimos um preço com cartão para esta embalagem. Os preços "
            "estimados estão no nosso site; mostre o cartão na farmácia para obter o "
            "preço final."
        ),
        "otherQuantities": "Preços com cartão que vimos para outras quantidades:",
        "needsZip": (
            "Digite um código ZIP para ver farmácias perto de você. Estes são preços "
            "com cartão por rede."
        ),
        "notInsurance": "Não é seguro",
        "cardTitle": "Cartão de desconto para receitas",
        "cardSub": "Grátis · sem cadastro · mostre ao farmacêutico",
        "howToTitle": "No balcão da farmácia",
        "step1": "Mostre o cartão ou informe BIN, PCN e Group.",
        "step2": "Peça para processar como cartão de desconto, não como seguro.",
        "step3": "Pergunte o preço com o cartão e sem ele, e pague o menor.",
        "moreChainOne": "+ 1 rede",
        "loading": "Carregando preços…",
        "error": "Os preços não carregaram. O cartão continua funcionando.",
        "storeInStore": "farmácia dentro da loja (não verificado)",
        "noStock": "Não vemos o estoque — ligue para a farmácia antes de ir.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Grupo",
        "zipGo": "OK",
        "zipInvalid": "Digite um código ZIP de 5 dígitos",
        "other": "Outra",
        "wallet": "Carteira (cartão para imprimir)",
        "emailPlaceholder": "Seu e-mail",
        "emailSend": "Enviar cartão",
        "emailConsent": (
            "Enviaremos um único e-mail com seu cartão. Não guardamos seu endereço e "
            "não enviaremos outros e-mails."
        ),
        "sending": "Enviando…",
        "emailSent": "Enviado — verifique sua caixa de entrada",
        "emailError": "Não foi possível enviar — tente novamente",
        "actionError": "Não carregou. Tente novamente.",
        "directions": "Como chegar",
        "allFamilies": "Todas",
        "pharmaciesTitle": "Farmácias próximas",
        "pricesWithoutStores": "Preço com cartão, sem loja próxima:",
        "showMore": "Mostrar mais {n}",
        "close": "Fechar",
        "noPriceShort": "sem preço com cartão",
        "priceAt": "{price} {withCard} na {name}",
    },
    "ht": {
        "pricesTitle": "Pri ak kat FineRx la, soti nan pi ba rive nan pi wo",
        "nearLabel": "Toupre {place}",
        "approx": "(apeprè)",
        "changeZip": "chanje kòd ZIP",
        "zipPlaceholder": "Kòd ZIP",
        "withCard": "ak kat la",
        "observed": "obsève {date}",
        "miles": "{n} mi",
        "moreChains": "+ {n} lòt chèn",
        "allPharmacies": "Tout famasi yo",
        "showAtCounter": "Montre l nan kontwa a",
        "save": "Sove",
        "print": "Enprime",
        "email": "Imèl",
        "sms": "Mesaj tèks",
        "copy": "Kopye",
        "copied": "Li kopye",
        "noPrice": (
            "Nou poko wè yon pri ak kat la pou pakè sa a. Pri estime yo sou sit nou an; "
            "montre kat la nan famasi a pou w jwenn pri final la."
        ),
        "otherQuantities": "Pri ak kat la nou wè pou lòt kantite:",
        "needsZip": (
            "Antre yon kòd ZIP pou w wè famasi ki toupre w. Sa yo se pri ak kat la "
            "pa chèn."
        ),
        "notInsurance": "Se pa yon asirans",
        "cardTitle": "Kat rabè pou preskripsyon",
        "cardSub": "Gratis · pa bezwen enskri · montre famasyen an li",
        "howToTitle": "Nan kontwa famasi a",
        "step1": "Montre kat la oswa li BIN, PCN ak Group.",
        "step2": "Mande pou yo pase l kòm kat rabè, pa kòm asirans.",
        "step3": "Mande pri a ak kat la ak san li, epi peye pi piti a.",
        "moreChainOne": "+ 1 lòt chèn",
        "loading": "N ap chaje pri yo…",
        "error": "Pri yo pa chaje. Kat la mache kanmenm.",
        "storeInStore": "famasi nan magazen an (pa verifye)",
        "noStock": "Nou pa wè estòk la — rele famasi a anvan w ale.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Gwoup",
        "zipGo": "OK",
        "zipInvalid": "Antre yon kòd ZIP 5 chif",
        "other": "Lòt",
        "wallet": "Bous (kat pou enprime)",
        "emailPlaceholder": "Imèl ou",
        "emailSend": "Voye kat la",
        "emailConsent": (
            "N ap voye yon sèl imèl ak kat ou a. Nou pa kenbe adrès ou epi nou p ap "
            "voye w imèl ankò."
        ),
        "sending": "N ap voye…",
        "emailSent": "Li voye — gade bwat resepsyon w",
        "emailError": "Li pa t ka voye — eseye ankò",
        "actionError": "Li pa chaje. Eseye ankò.",
        "directions": "Direksyon",
        "allFamilies": "Tout",
        "pharmaciesTitle": "Famasi ki toupre",
        "pricesWithoutStores": "Pri ak kat la, pa gen magazen toupre:",
        "showMore": "Montre {n} ankò",
        "close": "Fèmen",
        "noPriceShort": "pa wè pri ak kat",
        "priceAt": "{price} {withCard} nan {name}",
    },
    "fr": {
        "pricesTitle": "Prix avec la carte FineRx, par ordre croissant",
        "nearLabel": "Près de {place}",
        "approx": "(approximatif)",
        "changeZip": "modifier le code ZIP",
        "zipPlaceholder": "Code ZIP",
        "withCard": "avec la carte",
        "observed": "observé le {date}",
        "miles": "{n} mi",
        "moreChains": "+ {n} autres chaînes",
        "allPharmacies": "Toutes les pharmacies",
        "showAtCounter": "Montrer au comptoir",
        "save": "Enregistrer",
        "print": "Imprimer",
        "email": "E-mail",
        "sms": "SMS",
        "copy": "Copier",
        "copied": "Copié",
        "noPrice": (
            "Nous n'avons pas encore vu de prix avec la carte pour ce conditionnement. "
            "Les prix estimés sont sur notre site ; présentez la carte à la pharmacie "
            "pour obtenir le prix final."
        ),
        "otherQuantities": "Prix avec la carte observés pour d'autres quantités :",
        "needsZip": (
            "Saisissez un code ZIP pour voir les pharmacies près de chez vous. Ce sont "
            "des prix avec la carte par chaîne."
        ),
        "notInsurance": "Pas une assurance",
        "cardTitle": "Carte de réduction sur ordonnance",
        "cardSub": "Gratuite · sans inscription · montrez-la au pharmacien",
        "howToTitle": "Au comptoir de la pharmacie",
        "step1": "Montrez la carte ou dictez BIN, PCN et Group.",
        "step2": "Demandez de l’utiliser comme carte de réduction, pas comme assurance.",
        "step3": "Demandez le prix avec et sans la carte, et payez le moins élevé.",
        "moreChainOne": "+ 1 chaîne de plus",
        "loading": "Chargement des prix…",
        "error": "Les prix ne se sont pas chargés. La carte fonctionne quand même.",
        "storeInStore": "pharmacie en magasin (non vérifié)",
        "noStock": "Nous ne voyons pas les stocks — appelez la pharmacie avant d'y aller.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Groupe",
        "zipGo": "OK",
        "zipInvalid": "Saisissez un code ZIP à 5 chiffres",
        "other": "Autre",
        "wallet": "Portefeuille (carte imprimable)",
        "emailPlaceholder": "Votre e-mail",
        "emailSend": "Envoyer la carte",
        "emailConsent": (
            "Nous enverrons un seul e-mail avec votre carte. Nous ne conservons pas "
            "votre adresse et ne vous écrirons plus."
        ),
        "sending": "Envoi…",
        "emailSent": "Envoyé — consultez votre boîte de réception",
        "emailError": "Échec de l'envoi — réessayez",
        "actionError": "Le chargement a échoué. Réessayez.",
        "directions": "Itinéraire",
        "allFamilies": "Toutes",
        "pharmaciesTitle": "Pharmacies à proximité",
        "pricesWithoutStores": "Prix avec la carte, aucun magasin à proximité :",
        "showMore": "Afficher {n} de plus",
        "close": "Fermer",
        "noPriceShort": "aucun prix avec la carte",
        "priceAt": "{price} {withCard} chez {name}",
    },
    "tr": {
        "pricesTitle": "FineRx kartıyla fiyat, düşükten yükseğe",
        "nearLabel": "{place} yakınında",
        "approx": "(yaklaşık)",
        "changeZip": "ZIP kodunu değiştir",
        "zipPlaceholder": "ZIP kodu",
        "withCard": "kartla",
        "observed": "{date} tarihinde gözlemlendi",
        "miles": "{n} mil",
        "moreChains": "+ {n} zincir daha",
        "allPharmacies": "Tüm eczaneler",
        "showAtCounter": "Kasada göster",
        "save": "Kaydet",
        "print": "Yazdır",
        "email": "E-posta",
        "sms": "Kısa mesaj",
        "copy": "Kopyala",
        "copied": "Kopyalandı",
        "noPrice": (
            "Bu paket için henüz kartla bir fiyat görmedik. Tahmini fiyatlar sitemizde; "
            "nihai fiyatı öğrenmek için kartı eczanede gösterin."
        ),
        "otherQuantities": "Başka miktarlar için gördüğümüz kartla fiyatlar:",
        "needsZip": (
            "Yakınınızdaki eczaneleri görmek için bir ZIP kodu girin. Bunlar zincire "
            "göre kartla fiyatlardır."
        ),
        "notInsurance": "Sigorta değildir",
        "cardTitle": "Reçeteli İlaç İndirim Kartı",
        "cardSub": "Ücretsiz · kayıt gerekmez · eczacıya gösterin",
        "howToTitle": "Eczane tezgâhında",
        "step1": "Kartı gösterin ya da BIN, PCN ve Group kodlarını okuyun.",
        "step2": "Sigorta olarak değil, indirim kartı olarak işlenmesini isteyin.",
        "step3": "Kartlı ve kartsız fiyatı sorun, düşük olanı ödeyin.",
        "moreChainOne": "+ 1 zincir daha",
        "loading": "Fiyatlar yükleniyor…",
        "error": "Fiyatlar yüklenemedi. Kart yine de geçerli.",
        "storeInStore": "mağaza içi eczane (doğrulanmadı)",
        "noStock": "Stok durumunu göremiyoruz — gitmeden önce eczaneyi arayın.",
        "bin": "BIN",
        "pcn": "PCN",
        "group": "Grup",
        "zipGo": "Tamam",
        "zipInvalid": "5 haneli bir ZIP kodu girin",
        "other": "Diğer",
        "wallet": "Cüzdan (yazdırılabilir kart)",
        "emailPlaceholder": "E-posta adresiniz",
        "emailSend": "Kartı gönder",
        "emailConsent": (
            "Kartınızla birlikte tek bir e-posta göndereceğiz. Adresinizi saklamıyoruz "
            "ve size tekrar e-posta göndermeyeceğiz."
        ),
        "sending": "Gönderiliyor…",
        "emailSent": "Gönderildi — gelen kutunuzu kontrol edin",
        "emailError": "Gönderilemedi — tekrar deneyin",
        "actionError": "Yüklenemedi. Tekrar deneyin.",
        "directions": "Yol tarifi",
        "allFamilies": "Tümü",
        "pharmaciesTitle": "Yakındaki eczaneler",
        "pricesWithoutStores": "Kartla fiyat var, yakında mağaza yok:",
        "showMore": "{n} tane daha göster",
        "close": "Kapat",
        "noPriceShort": "kartla fiyat görülmedi",
        "priceAt": "{name}: {price} ({withCard})",
    },
}

# --- phase 2 (MCP 2.1, contract C2'): search / map / where / equivalent / rx ---
# The keys the 2.1 widget draws (``widget-src/src/labels.ts`` FALLBACK_LABELS,
# "phase 2" block). Merged into EN / _T below so every locale carries all of
# them; ``tests/test_phase2.py`` checks the widget's key list against EN.
PHASE2_EN: dict[str, str] = {
    "where": "Where:",
    "wherePlaceholder": "ZIP, city or address",
    "changeWhere": "change location",
    "whereInvalid": "Enter a 5-digit ZIP code, a city or an address",
    "needsWhere": (
        "Enter a ZIP code, a city or an address to see pharmacies near you. These are card prices by chain."
    ),
    "whereNote": "An address is sent once to the US Census geocoder to find pharmacies nearby. We don't store it.",
    "inn": "Active ingredient",
    "searchTitle": "Find a medicine",
    "searchPlaceholder": "Medicine, or a brand from your country",
    "openSearch": "Search",
    "popular": "Often searched:",
    "searching": "Searching…",
    "noResults": "Nothing found. Try the active ingredient, or check the spelling.",
    "fromWithCard": "with card from {price} · {date}",
    "kindGeneric": "generic",
    "kindBrand": "brand",
    "foreignBrand": "foreign brand",
    "inUs": "in the US: {name}",
    "noUsProduct": "no US product listed",
    "backToSearch": "Back to search",
    "back": "Back",
    "onMap": "On the map",
    "listView": "List",
    "you": "You",
    "mapTitle": "Pharmacies on a map",
    "mapRange": "Range",
    "offMap": "{n} farther than {r} mi — in the list",
    "equivalentUs": "In the US",
    "usClassSameInn": "same active ingredient",
    "usClassRxAlternative": "not sold in the US as the same product",
    "usClassNoEquivalent": "no US equivalent",
    "sameInnNote": "Same active ingredient is not the same product — ask a pharmacist.",
    "pricesInUs": "Prices in the US",
    "rxTitle": "How to get a prescription: {name}",
    "rxTitleAny": "How to get a prescription",
    "rxRestricted": (
        "For this medicine FineRx shows only card prices and the free card. "
        "Discuss treatment with a licensed clinician."
    ),
    "pricesWithCard": "Prices with the card",
    "withoutInsurance": "Without insurance:",
}

_PHASE2: dict[str, dict[str, str]] = {
    "es": {
        "where": "Dónde:",
        "wherePlaceholder": "Código postal, ciudad o dirección",
        "changeWhere": "cambiar ubicación",
        "whereInvalid": "Ingrese un código postal de 5 dígitos, una ciudad o una dirección",
        "needsWhere": (
            "Ingrese un código postal, una ciudad o una dirección para ver farmacias cerca de usted. "
            "Estos son precios con tarjeta por cadena."
        ),
        "whereNote": "La dirección se envía una sola vez al geocodificador del Censo de EE. UU. para buscar farmacias cercanas. No la guardamos.",
        "inn": "Principio activo",
        "searchTitle": "Buscar un medicamento",
        "searchPlaceholder": "Medicamento, o una marca de su país",
        "openSearch": "Buscar",
        "popular": "Búsquedas frecuentes:",
        "searching": "Buscando…",
        "noResults": "No se encontró nada. Pruebe con el principio activo o revise la ortografía.",
        "fromWithCard": "con tarjeta desde {price} · {date}",
        "kindGeneric": "genérico",
        "kindBrand": "marca",
        "foreignBrand": "marca extranjera",
        "inUs": "en EE. UU.: {name}",
        "noUsProduct": "sin producto en EE. UU.",
        "backToSearch": "Volver a la búsqueda",
        "back": "Atrás",
        "onMap": "En el mapa",
        "listView": "Lista",
        "you": "Usted",
        "mapTitle": "Farmacias en un mapa",
        "mapRange": "Radio",
        "offMap": "{n} a más de {r} mi — en la lista",
        "equivalentUs": "En EE. UU.",
        "usClassSameInn": "mismo principio activo",
        "usClassRxAlternative": "no se vende en EE. UU. como el mismo producto",
        "usClassNoEquivalent": "sin equivalente en EE. UU.",
        "sameInnNote": "El mismo principio activo no es el mismo producto: consulte a un farmacéutico.",
        "pricesInUs": "Precios en EE. UU.",
        "rxTitle": "Cómo obtener una receta: {name}",
        "rxTitleAny": "Cómo obtener una receta",
        "rxRestricted": (
            "Para este medicamento, FineRx muestra solo los precios con tarjeta y la tarjeta gratuita. "
            "Hable del tratamiento con un profesional de salud autorizado."
        ),
        "pricesWithCard": "Precios con la tarjeta",
        "withoutInsurance": "Sin seguro:",
    },
    "zh": {
        "where": "地点：",
        "wherePlaceholder": "邮编、城市或地址",
        "changeWhere": "更改地点",
        "whereInvalid": "请输入 5 位邮政编码、城市或地址",
        "needsWhere": "输入邮政编码、城市或地址即可查看附近的药房。以下为各连锁药房的用卡价格。",
        "whereNote": "地址仅发送一次给美国人口普查局的地理编码服务，用于查找附近的药房。我们不会保存。",
        "inn": "活性成分",
        "searchTitle": "查找药品",
        "searchPlaceholder": "药品名称，或您所在国家的品牌",
        "openSearch": "搜索",
        "popular": "常见搜索：",
        "searching": "正在搜索…",
        "noResults": "未找到结果。请尝试输入活性成分，或检查拼写。",
        "fromWithCard": "用卡 {price} 起 · {date}",
        "kindGeneric": "仿制药",
        "kindBrand": "品牌药",
        "foreignBrand": "外国品牌",
        "inUs": "在美国：{name}",
        "noUsProduct": "美国无对应产品",
        "backToSearch": "返回搜索",
        "back": "返回",
        "onMap": "在地图上查看",
        "listView": "列表",
        "you": "您",
        "mapTitle": "地图上的药房",
        "mapRange": "范围",
        "offMap": "{n} 家超过 {r} 英里 — 见列表",
        "equivalentUs": "在美国",
        "usClassSameInn": "相同活性成分",
        "usClassRxAlternative": "在美国不作为同一产品销售",
        "usClassNoEquivalent": "美国无对应药品",
        "sameInnNote": "活性成分相同不等于产品相同——请咨询药剂师。",
        "pricesInUs": "美国价格",
        "rxTitle": "如何获得处方：{name}",
        "rxTitleAny": "如何获得处方",
        "rxRestricted": "对于此药品，FineRx 仅显示用卡价格和免费卡。请与持证医生讨论治疗方案。",
        "pricesWithCard": "用卡价格",
        "withoutInsurance": "无保险：",
    },
    "vi": {
        "where": "Ở đâu:",
        "wherePlaceholder": "Mã ZIP, thành phố hoặc địa chỉ",
        "changeWhere": "đổi địa điểm",
        "whereInvalid": "Nhập mã ZIP gồm 5 chữ số, thành phố hoặc địa chỉ",
        "needsWhere": (
            "Nhập mã ZIP, thành phố hoặc địa chỉ để xem các nhà thuốc gần bạn. Đây là giá với thẻ theo chuỗi."
        ),
        "whereNote": "Địa chỉ chỉ được gửi một lần đến dịch vụ mã hóa địa lý của Cục Điều tra Dân số Hoa Kỳ để tìm nhà thuốc gần đây. Chúng tôi không lưu lại.",
        "inn": "Hoạt chất",
        "searchTitle": "Tìm thuốc",
        "searchPlaceholder": "Tên thuốc, hoặc nhãn hiệu từ nước bạn",
        "openSearch": "Tìm kiếm",
        "popular": "Thường được tìm:",
        "searching": "Đang tìm…",
        "noResults": "Không tìm thấy. Hãy thử hoạt chất, hoặc kiểm tra chính tả.",
        "fromWithCard": "với thẻ từ {price} · {date}",
        "kindGeneric": "thuốc gốc",
        "kindBrand": "biệt dược",
        "foreignBrand": "nhãn hiệu nước ngoài",
        "inUs": "tại Mỹ: {name}",
        "noUsProduct": "không có sản phẩm tại Mỹ",
        "backToSearch": "Quay lại tìm kiếm",
        "back": "Quay lại",
        "onMap": "Trên bản đồ",
        "listView": "Danh sách",
        "you": "Bạn",
        "mapTitle": "Nhà thuốc trên bản đồ",
        "mapRange": "Phạm vi",
        "offMap": "{n} nơi xa hơn {r} mi — trong danh sách",
        "equivalentUs": "Tại Mỹ",
        "usClassSameInn": "cùng hoạt chất",
        "usClassRxAlternative": "không bán tại Mỹ như cùng một sản phẩm",
        "usClassNoEquivalent": "không có thuốc tương đương tại Mỹ",
        "sameInnNote": "Cùng hoạt chất không có nghĩa là cùng sản phẩm — hãy hỏi dược sĩ.",
        "pricesInUs": "Giá tại Mỹ",
        "rxTitle": "Cách có đơn thuốc: {name}",
        "rxTitleAny": "Cách có đơn thuốc",
        "rxRestricted": (
            "Với thuốc này, FineRx chỉ hiển thị giá với thẻ và thẻ miễn phí. "
            "Hãy trao đổi về việc điều trị với bác sĩ có giấy phép."
        ),
        "pricesWithCard": "Giá với thẻ",
        "withoutInsurance": "Không có bảo hiểm:",
    },
    "tl": {
        "where": "Saan:",
        "wherePlaceholder": "ZIP, lungsod o address",
        "changeWhere": "palitan ang lokasyon",
        "whereInvalid": "Maglagay ng 5-digit na ZIP code, lungsod o address",
        "needsWhere": (
            "Maglagay ng ZIP code, lungsod o address para makita ang mga botika malapit sa iyo. "
            "Ito ang mga presyo gamit ang card ayon sa chain."
        ),
        "whereNote": "Ipinapadala nang isang beses ang address sa geocoder ng US Census para maghanap ng botika sa malapit. Hindi namin ito itinatago.",
        "inn": "Aktibong sangkap",
        "searchTitle": "Maghanap ng gamot",
        "searchPlaceholder": "Gamot, o brand mula sa iyong bansa",
        "openSearch": "Maghanap",
        "popular": "Madalas hanapin:",
        "searching": "Naghahanap…",
        "noResults": "Walang nahanap. Subukan ang active ingredient, o suriin ang baybay.",
        "fromWithCard": "gamit ang card mula {price} · {date}",
        "kindGeneric": "generic",
        "kindBrand": "brand",
        "foreignBrand": "banyagang brand",
        "inUs": "sa US: {name}",
        "noUsProduct": "walang produkto sa US",
        "backToSearch": "Bumalik sa paghahanap",
        "back": "Bumalik",
        "onMap": "Sa mapa",
        "listView": "Listahan",
        "you": "Ikaw",
        "mapTitle": "Mga botika sa mapa",
        "mapRange": "Layo",
        "offMap": "{n} na lampas {r} mi — nasa listahan",
        "equivalentUs": "Sa US",
        "usClassSameInn": "parehong active ingredient",
        "usClassRxAlternative": "hindi ibinebenta sa US bilang parehong produkto",
        "usClassNoEquivalent": "walang katumbas sa US",
        "sameInnNote": (
            "Ang parehong active ingredient ay hindi nangangahulugang parehong produkto — "
            "magtanong sa parmasyutiko."
        ),
        "pricesInUs": "Mga presyo sa US",
        "rxTitle": "Paano kumuha ng reseta: {name}",
        "rxTitleAny": "Paano kumuha ng reseta",
        "rxRestricted": (
            "Para sa gamot na ito, ipinapakita lang ng FineRx ang mga presyo gamit ang card at ang libreng card. "
            "Pag-usapan ang gamutan kasama ang lisensyadong clinician."
        ),
        "pricesWithCard": "Mga presyo gamit ang card",
        "withoutInsurance": "Walang insurance:",
    },
    "ar": {
        "where": "المكان:",
        "wherePlaceholder": "الرمز البريدي أو المدينة أو العنوان",
        "changeWhere": "تغيير الموقع",
        "whereInvalid": "أدخل رمزًا بريديًا من 5 أرقام أو مدينة أو عنوانًا",
        "needsWhere": (
            "أدخل رمزًا بريديًا أو مدينة أو عنوانًا لرؤية الصيدليات القريبة منك. هذه أسعار بالبطاقة حسب السلسلة."
        ),
        "whereNote": "يُرسَل العنوان مرة واحدة إلى خدمة الترميز الجغرافي لمكتب الإحصاء الأمريكي للعثور على الصيدليات القريبة. لا نحتفظ به.",
        "inn": "المادة الفعالة",
        "searchTitle": "ابحث عن دواء",
        "searchPlaceholder": "اسم الدواء، أو علامة تجارية من بلدك",
        "openSearch": "بحث",
        "popular": "عمليات بحث شائعة:",
        "searching": "جارٍ البحث…",
        "noResults": "لم يُعثر على شيء. جرّب المادة الفعالة أو تحقق من التهجئة.",
        "fromWithCard": "بالبطاقة من {price} · {date}",
        "kindGeneric": "دواء جنيس",
        "kindBrand": "علامة تجارية",
        "foreignBrand": "علامة تجارية أجنبية",
        "inUs": "في الولايات المتحدة: {name}",
        "noUsProduct": "لا يوجد منتج مدرج في الولايات المتحدة",
        "backToSearch": "العودة إلى البحث",
        "back": "رجوع",
        "onMap": "على الخريطة",
        "listView": "قائمة",
        "you": "أنت",
        "mapTitle": "الصيدليات على الخريطة",
        "mapRange": "النطاق",
        "offMap": "{n} أبعد من {r} ميل — في القائمة",
        "equivalentUs": "في الولايات المتحدة",
        "usClassSameInn": "المادة الفعالة نفسها",
        "usClassRxAlternative": "لا يُباع في الولايات المتحدة كالمنتج نفسه",
        "usClassNoEquivalent": "لا يوجد مكافئ في الولايات المتحدة",
        "sameInnNote": "المادة الفعالة نفسها لا تعني المنتج نفسه — اسأل الصيدلي.",
        "pricesInUs": "الأسعار في الولايات المتحدة",
        "rxTitle": "كيف تحصل على وصفة طبية: {name}",
        "rxTitleAny": "كيف تحصل على وصفة طبية",
        "rxRestricted": "لهذا الدواء، يعرض FineRx أسعار البطاقة والبطاقة المجانية فقط. ناقش العلاج مع طبيب مرخّص.",
        "pricesWithCard": "الأسعار بالبطاقة",
        "withoutInsurance": "بدون تأمين:",
    },
    "ko": {
        "where": "위치:",
        "wherePlaceholder": "ZIP, 도시 또는 주소",
        "changeWhere": "위치 변경",
        "whereInvalid": "5자리 ZIP 코드, 도시 또는 주소를 입력하세요",
        "needsWhere": "근처 약국을 보려면 ZIP 코드, 도시 또는 주소를 입력하세요. 체인별 카드 적용 가격입니다.",
        "whereNote": "주소는 근처 약국을 찾기 위해 미국 인구조사국 지오코더에 한 번만 전송되며 저장하지 않습니다.",
        "inn": "유효 성분",
        "searchTitle": "약 찾기",
        "searchPlaceholder": "약 이름 또는 본국의 브랜드",
        "openSearch": "검색",
        "popular": "자주 찾는 약:",
        "searching": "검색 중…",
        "noResults": "결과가 없습니다. 유효 성분으로 검색하거나 철자를 확인하세요.",
        "fromWithCard": "카드 적용 {price}부터 · {date}",
        "kindGeneric": "제네릭",
        "kindBrand": "브랜드",
        "foreignBrand": "해외 브랜드",
        "inUs": "미국에서: {name}",
        "noUsProduct": "미국 제품 없음",
        "backToSearch": "검색으로 돌아가기",
        "back": "뒤로",
        "onMap": "지도에서 보기",
        "listView": "목록",
        "you": "내 위치",
        "mapTitle": "지도 위의 약국",
        "mapRange": "범위",
        "offMap": "{r}마일보다 먼 {n}곳 — 목록에 있음",
        "equivalentUs": "미국에서",
        "usClassSameInn": "같은 유효 성분",
        "usClassRxAlternative": "미국에서 같은 제품으로 판매되지 않음",
        "usClassNoEquivalent": "미국 대응 제품 없음",
        "sameInnNote": "유효 성분이 같아도 같은 제품은 아닙니다 — 약사에게 문의하세요.",
        "pricesInUs": "미국 가격",
        "rxTitle": "처방전 받는 방법: {name}",
        "rxTitleAny": "처방전 받는 방법",
        "rxRestricted": (
            "이 약의 경우 FineRx는 카드 적용 가격과 무료 카드만 보여 줍니다. 치료는 면허가 있는 의료인과 상의하세요."
        ),
        "pricesWithCard": "카드 적용 가격",
        "withoutInsurance": "보험 없이:",
    },
    "ru": {
        "where": "Где:",
        "wherePlaceholder": "ZIP, город или адрес",
        "changeWhere": "изменить место",
        "whereInvalid": "Введите ZIP-код из 5 цифр, город или адрес",
        "needsWhere": "Введите ZIP-код, город или адрес, чтобы увидеть аптеки рядом. Это цены по карте по сетям.",
        "whereNote": "Адрес один раз отправляется в геокодер Бюро переписи США, чтобы найти аптеки рядом. Мы его не храним.",
        "inn": "Действующее вещество",
        "searchTitle": "Найти лекарство",
        "searchPlaceholder": "Лекарство или бренд из вашей страны",
        "openSearch": "Поиск",
        "popular": "Часто ищут:",
        "searching": "Ищем…",
        "noResults": "Ничего не нашлось. Попробуйте действующее вещество или проверьте написание.",
        "fromWithCard": "с картой от {price} · {date}",
        "kindGeneric": "дженерик",
        "kindBrand": "бренд",
        "foreignBrand": "зарубежный бренд",
        "inUs": "в США: {name}",
        "noUsProduct": "в США такого продукта нет",
        "backToSearch": "Назад к поиску",
        "back": "Назад",
        "onMap": "На схеме",
        "listView": "Список",
        "you": "Вы",
        "mapTitle": "Аптеки на схеме",
        "mapRange": "Радиус",
        "offMap": "{n} дальше {r} миль — в списке",
        "equivalentUs": "В США",
        "usClassSameInn": "то же действующее вещество",
        "usClassRxAlternative": "в США не продаётся как тот же продукт",
        "usClassNoEquivalent": "аналога в США нет",
        "sameInnNote": "Одно действующее вещество — не тот же продукт. Спросите фармацевта.",
        "pricesInUs": "Цены в США",
        "rxTitle": "Как получить рецепт: {name}",
        "rxTitleAny": "Как получить рецепт",
        "rxRestricted": (
            "Для этого лекарства FineRx показывает только цены с картой и бесплатную карту. "
            "Лечение обсудите с лицензированным врачом."
        ),
        "pricesWithCard": "Цены с картой",
        "withoutInsurance": "Без страховки:",
    },
    "pt": {
        "where": "Onde:",
        "wherePlaceholder": "Código ZIP, cidade ou endereço",
        "changeWhere": "alterar local",
        "whereInvalid": "Digite um código ZIP de 5 dígitos, uma cidade ou um endereço",
        "needsWhere": (
            "Digite um código ZIP, uma cidade ou um endereço para ver farmácias perto de você. "
            "Estes são preços com cartão por rede."
        ),
        "whereNote": "O endereço é enviado uma única vez ao geocodificador do Censo dos EUA para encontrar farmácias próximas. Não o guardamos.",
        "inn": "Princípio ativo",
        "searchTitle": "Buscar um medicamento",
        "searchPlaceholder": "Medicamento, ou uma marca do seu país",
        "openSearch": "Buscar",
        "popular": "Buscas frequentes:",
        "searching": "Buscando…",
        "noResults": "Nada encontrado. Tente o princípio ativo ou verifique a grafia.",
        "fromWithCard": "com cartão a partir de {price} · {date}",
        "kindGeneric": "genérico",
        "kindBrand": "marca",
        "foreignBrand": "marca estrangeira",
        "inUs": "nos EUA: {name}",
        "noUsProduct": "sem produto nos EUA",
        "backToSearch": "Voltar à busca",
        "back": "Voltar",
        "onMap": "No mapa",
        "listView": "Lista",
        "you": "Você",
        "mapTitle": "Farmácias no mapa",
        "mapRange": "Raio",
        "offMap": "{n} a mais de {r} mi — na lista",
        "equivalentUs": "Nos EUA",
        "usClassSameInn": "mesmo princípio ativo",
        "usClassRxAlternative": "não é vendido nos EUA como o mesmo produto",
        "usClassNoEquivalent": "sem equivalente nos EUA",
        "sameInnNote": "O mesmo princípio ativo não é o mesmo produto — pergunte ao farmacêutico.",
        "pricesInUs": "Preços nos EUA",
        "rxTitle": "Como obter uma receita: {name}",
        "rxTitleAny": "Como obter uma receita",
        "rxRestricted": (
            "Para este medicamento, a FineRx mostra apenas os preços com cartão e o cartão gratuito. "
            "Converse sobre o tratamento com um profissional de saúde licenciado."
        ),
        "pricesWithCard": "Preços com o cartão",
        "withoutInsurance": "Sem seguro:",
    },
    "ht": {
        "where": "Ki kote:",
        "wherePlaceholder": "Kòd ZIP, vil oswa adrès",
        "changeWhere": "chanje kote",
        "whereInvalid": "Antre yon kòd ZIP 5 chif, yon vil oswa yon adrès",
        "needsWhere": (
            "Antre yon kòd ZIP, yon vil oswa yon adrès pou w wè famasi ki toupre w. "
            "Sa yo se pri ak kat la pa chèn."
        ),
        "whereNote": "Nou voye adrès la yon sèl fwa bay jeyokodè Resansman Ameriken an pou jwenn famasi ki toupre. Nou pa kenbe l.",
        "inn": "Engredyan aktif",
        "searchTitle": "Chèche yon medikaman",
        "searchPlaceholder": "Medikaman, oswa yon mak ki soti nan peyi w",
        "openSearch": "Chèche",
        "popular": "Moun chèche souvan:",
        "searching": "N ap chèche…",
        "noResults": "Nou pa jwenn anyen. Eseye engredyan aktif la, oswa verifye jan w ekri l.",
        "fromWithCard": "ak kat la apati {price} · {date}",
        "kindGeneric": "jenerik",
        "kindBrand": "mak",
        "foreignBrand": "mak etranje",
        "inUs": "Ozetazini: {name}",
        "noUsProduct": "pa gen pwodui Ozetazini",
        "backToSearch": "Retounen nan rechèch la",
        "back": "Retounen",
        "onMap": "Sou kat jeyografik la",
        "listView": "Lis",
        "you": "Ou",
        "mapTitle": "Famasi sou yon kat jeyografik",
        "mapRange": "Distans",
        "offMap": "{n} pi lwen pase {r} mi — nan lis la",
        "equivalentUs": "Ozetazini",
        "usClassSameInn": "menm engredyan aktif",
        "usClassRxAlternative": "yo pa vann li Ozetazini kòm menm pwodui a",
        "usClassNoEquivalent": "pa gen ekivalan Ozetazini",
        "sameInnNote": "Menm engredyan aktif pa vle di menm pwodui — mande famasyen an.",
        "pricesInUs": "Pri Ozetazini",
        "rxTitle": "Kijan pou jwenn yon preskripsyon: {name}",
        "rxTitleAny": "Kijan pou jwenn yon preskripsyon",
        "rxRestricted": (
            "Pou medikaman sa a, FineRx montre sèlman pri ak kat la ak kat gratis la. "
            "Pale sou tretman an ak yon klinisyen ki gen lisans."
        ),
        "pricesWithCard": "Pri ak kat la",
        "withoutInsurance": "San asirans:",
    },
    "fr": {
        "where": "Où :",
        "wherePlaceholder": "Code ZIP, ville ou adresse",
        "changeWhere": "modifier le lieu",
        "whereInvalid": "Saisissez un code ZIP à 5 chiffres, une ville ou une adresse",
        "needsWhere": (
            "Saisissez un code ZIP, une ville ou une adresse pour voir les pharmacies près de chez vous. "
            "Ce sont des prix avec la carte par chaîne."
        ),
        "whereNote": "L'adresse est envoyée une seule fois au géocodeur du Bureau du recensement des États-Unis pour trouver les pharmacies proches. Nous ne la conservons pas.",
        "inn": "Principe actif",
        "searchTitle": "Trouver un médicament",
        "searchPlaceholder": "Médicament, ou une marque de votre pays",
        "openSearch": "Rechercher",
        "popular": "Recherches fréquentes :",
        "searching": "Recherche…",
        "noResults": "Aucun résultat. Essayez le principe actif ou vérifiez l’orthographe.",
        "fromWithCard": "avec la carte dès {price} · {date}",
        "kindGeneric": "générique",
        "kindBrand": "marque",
        "foreignBrand": "marque étrangère",
        "inUs": "aux États-Unis : {name}",
        "noUsProduct": "aucun produit aux États-Unis",
        "backToSearch": "Retour à la recherche",
        "back": "Retour",
        "onMap": "Sur le plan",
        "listView": "Liste",
        "you": "Vous",
        "mapTitle": "Pharmacies sur un plan",
        "mapRange": "Rayon",
        "offMap": "{n} au-delà de {r} mi — dans la liste",
        "equivalentUs": "Aux États-Unis",
        "usClassSameInn": "même principe actif",
        "usClassRxAlternative": "non vendu aux États-Unis comme le même produit",
        "usClassNoEquivalent": "pas d’équivalent aux États-Unis",
        "sameInnNote": "Le même principe actif n’est pas le même produit — demandez au pharmacien.",
        "pricesInUs": "Prix aux États-Unis",
        "rxTitle": "Comment obtenir une ordonnance : {name}",
        "rxTitleAny": "Comment obtenir une ordonnance",
        "rxRestricted": (
            "Pour ce médicament, FineRx affiche uniquement les prix avec la carte et la carte gratuite. "
            "Parlez du traitement avec un professionnel de santé agréé."
        ),
        "pricesWithCard": "Prix avec la carte",
        "withoutInsurance": "Sans assurance :",
    },
    "tr": {
        "where": "Konum:",
        "wherePlaceholder": "ZIP, şehir veya adres",
        "changeWhere": "konumu değiştir",
        "whereInvalid": "5 haneli bir ZIP kodu, bir şehir veya bir adres girin",
        "needsWhere": (
            "Yakınınızdaki eczaneleri görmek için bir ZIP kodu, şehir veya adres girin. "
            "Bunlar zincire göre kartla fiyatlardır."
        ),
        "whereNote": "Adres, yakındaki eczaneleri bulmak için ABD Nüfus Sayım Bürosu'nun coğrafi kodlayıcısına bir kez gönderilir. Saklamıyoruz.",
        "inn": "Etken madde",
        "searchTitle": "İlaç bul",
        "searchPlaceholder": "İlaç adı veya ülkenizdeki bir marka",
        "openSearch": "Ara",
        "popular": "Sık arananlar:",
        "searching": "Aranıyor…",
        "noResults": "Sonuç bulunamadı. Etken maddeyi deneyin veya yazımı kontrol edin.",
        "fromWithCard": "kartla {price} ve üzeri · {date}",
        "kindGeneric": "jenerik",
        "kindBrand": "marka",
        "foreignBrand": "yabancı marka",
        "inUs": "ABD'de: {name}",
        "noUsProduct": "ABD'de ürün yok",
        "backToSearch": "Aramaya dön",
        "back": "Geri",
        "onMap": "Haritada",
        "listView": "Liste",
        "you": "Siz",
        "mapTitle": "Haritada eczaneler",
        "mapRange": "Mesafe",
        "offMap": "{n} eczane {r} milden uzak — listede",
        "equivalentUs": "ABD'de",
        "usClassSameInn": "aynı etken madde",
        "usClassRxAlternative": "ABD'de aynı ürün olarak satılmıyor",
        "usClassNoEquivalent": "ABD'de karşılığı yok",
        "sameInnNote": "Aynı etken madde aynı ürün demek değildir — eczacıya danışın.",
        "pricesInUs": "ABD'deki fiyatlar",
        "rxTitle": "Reçete nasıl alınır: {name}",
        "rxTitleAny": "Reçete nasıl alınır",
        "rxRestricted": (
            "Bu ilaç için FineRx yalnızca kartla fiyatları ve ücretsiz kartı gösterir. "
            "Tedaviyi lisanslı bir hekimle konuşun."
        ),
        "pricesWithCard": "Kartla fiyatlar",
        "withoutInsurance": "Sigortasız:",
    },
}

EN.update(PHASE2_EN)
for _loc, _extra in _PHASE2.items():
    _T[_loc].update(_extra)

LOCALES: tuple[str, ...] = ("en", *_T)


def labels_for(locale: str) -> dict[str, str]:
    """Every key, in ``locale`` where we have it, English otherwise."""
    return {**EN, **_T.get(locale, {})}


# --- the words of ``content``: the markdown the MODEL reads ---------------------
#
# Headings and service phrases of every tool answer (views.py, server.py, the
# card block in card_law.py) in the reader's language — the prices, dates and
# codes are data and never translated. Full sets for en/es/ru; the other nine
# locales borrow the phrases that already exist as widget labels above (stock,
# "with card, observed", miles, pharmacies nearby, the ZIP hint) and read the
# rest in English. Placeholders ``{name}`` are filled by ``tr``; a value is
# never re-scanned for placeholders. Same rules as the widget set: translations
# of the English, no new promises, and the English is held to the card-law word
# bans by ``tests/test_card_law.py``.

TEXT_EN: dict[str, str] = {
    # prices and stores (views.py)
    "withCardObserved": "{price} with the card, observed {date}",
    "zonePrice": "{zone} price",
    "placeZip": "{where} (ZIP {zip})",
    "zipOnly": "ZIP {zip}",
    "placeApprox": "{where} (approximate)",
    "yourArea": "your area",
    "thisMedicine": "this medicine",
    "coverageOther": (
        "We have not seen a card price for {quantity}; card prices were seen for these "
        "quantities: {seen}. A price is never scaled to another quantity."
    ),
    "coverageNone": "We have not seen a card price for this package yet; the pharmacy gives the final price.",
    "pricesNational": (
        "Price with the free FineRx card by pharmacy chain across the US, low to high "
        "(no place given — a ZIP code shows the pharmacies nearby):"
    ),
    "pricesNear": "Price with the free FineRx card near {place}, low to high:",
    "nearestStore": "nearest store {miles} mi",
    "noPriceForPackage": "no card price seen for this package",
    "noPriceShort": "no card price seen",
    "moreChains": "… and {n} more chains in the full list.",
    "noChain": "No pharmacy chain with a card price for this package.",
    "noStoreNearby": "{name} (no store nearby): {price}",
    "perChain": "The card price is set per chain (Walmart: per state), so choose the chain, not the address.",
    "noStock": "We don't see stock — call the pharmacy before you go.",
    "restrictedPrices": "For this medicine FineRx shows card prices and the card only.",
    "pharmaciesNear": "Pharmacies near {place}",
    "pharmaciesNearby": "Pharmacies nearby",
    "noPlace": "No place given: share a 5-digit ZIP code to list the pharmacies nearby.",
    "noStoreInRange": "No store we can place within 30 miles.",
    "storeInStore": "pharmacy in store, not verified",
    "milesShort": "{n} mi",
    "moreNearby": "… and {n} more nearby.",
    "osm": "Store locations © OpenStreetMap contributors (ODbL).",
    "zipInvalid": "A ZIP code must be 5 digits — send a 5-digit ZIP code to see the pharmacies nearby.",
    # answers without data (server.py)
    "rateLimited": "Too many requests right now — try again in {n} s.",
    "loadFailed": "Prices didn't load right now. The card still works.",
    "busy": "Prices are busy right now — try again shortly. The card still works.",
    "drugRequired": "Name the medicine (for example “atorvastatin 20 mg”) to see card prices.",
    "noMatch": "No medicine matched “{query}”. Try search_drugs with another spelling.",
    "closeMatches": "No medicine matched “{query}”. Close matches: {names}.",
    "zipNotFound": "That ZIP code is not one we know. Try a nearby 5-digit ZIP.",
    # the card (get_savings_card, email_savings_card, card_law.law_block)
    "freeCard": "Free FineRx card",
    "cardTitle": "**The free FineRx discount card** — free, no signup, not insurance.",
    "howToUse": "How to use it:",
    "sayAtCounter": "Say at the counter: “{phrase}”",
    "cardLinks": "Card page: {site} · printable sheet: {print}",
    "cardPriceAt": "{package}: {price} with the card at {name}, observed {date}.",
    "noCardPriceFor": "No card price on file for “{drug}”; the card works the same.",
    "emailSent": "Sent the free FineRx card to {to}.",
    # the catalog tools
    "searchHead": "Search “{query}”: {n} match(es).",
    "noCardPriceYet": "no card price seen yet",
    "fromLine": "with the card from {price} for {package}, observed {date}",
    "foreignBrandLine": "Foreign brand {brand} ({countries}): active ingredient {inn} — call find_us_equivalent.",
    "strengthsLine": "Strengths and pack sizes with a card price: {forms}.",
    "noCardPriceAny": "No card price seen for any package of this medicine yet.",
    "cardFromLine": "Card price from {price} for {package}, observed {date}.",
    "defaultPackage": "Default package {label} — card price by chain:",
    "havePrescription": "Have a prescription:",
    "noPrescription": "No prescription yet:",
    "brandCostly": "Brand costs too much:",
    "noOptions": "No options on file.",
    "restrictedRx": (
        "For this medicine FineRx shows only card prices and the free card. "
        "Discuss treatment with a licensed clinician."
    ),
    "usDrugLine": "US drug: {name} (slug {slug}) — {price}.",
    "sameBrandElsewhere": "Same brand name elsewhere: {list}",
    "noForeignMatch": "No foreign brand matched “{brand}”. Try the active ingredient with search_drugs.",
    "brandsAbroad": "Brands abroad that resolve to {slug}: {n}.",
    # phase 2 (MCP 2.1): search, a typed place, the rx view
    "searchOpened": (
        "Opened the FineRx search in the card: the person types a medicine or a brand from another "
        "country, picks it and a place, and sees card prices by chain."
    ),
    "searchOpenedFor": "Opened the FineRx search for “{query}” in the card. Matches:",
    "searchNoMatch": "No medicine matched “{query}” yet — the person can refine it in the search field.",
    "searchPopular": "Often searched: {names}.",
    "suggestFrom": "with the card from {price}, observed {date}",
    "foreignSuggest": "Foreign brand {brand} ({countries}) — find_us_equivalent says what it is in the US.",
    "whereNotFound": (
        "We could not place that location — enter a 5-digit ZIP code, or a city with its state "
        "(for example “Austin, TX”)."
    ),
    "rxHave": "If you have a prescription",
    "rxNone": "If you don't have one yet",
    "rxBrand": "If the brand costs too much",
    "rxCardFrom": "Without insurance: with the card from {price} for {package}, observed {date}.",
}

_TEXT: dict[str, dict[str, str]] = {
    "es": {
        "withCardObserved": "{price} con la tarjeta, observado el {date}",
        "zonePrice": "precio de {zone}",
        "placeZip": "{where} (código postal {zip})",
        "zipOnly": "código postal {zip}",
        "placeApprox": "{where} (aproximado)",
        "yourArea": "su zona",
        "thisMedicine": "este medicamento",
        "coverageOther": (
            "No hemos visto un precio con tarjeta para {quantity}; se vieron precios con "
            "tarjeta para estas cantidades: {seen}. Un precio nunca se ajusta a otra cantidad."
        ),
        "coverageNone": (
            "Aún no hemos visto un precio con tarjeta para este paquete; la farmacia da el precio final."
        ),
        "pricesNational": (
            "Precio con la tarjeta gratuita FineRx por cadena de farmacias en todo EE. UU., "
            "de menor a mayor (sin lugar indicado: un código postal muestra las farmacias cercanas):"
        ),
        "pricesNear": "Precio con la tarjeta gratuita FineRx cerca de {place}, de menor a mayor:",
        "nearestStore": "tienda más cercana a {miles} mi",
        "noPriceForPackage": "no se ha visto un precio con tarjeta para este paquete",
        "noPriceShort": "no se ha visto un precio con tarjeta",
        "moreChains": "… y {n} cadenas más en la lista completa.",
        "noChain": "Ninguna cadena de farmacias tiene un precio con tarjeta para este paquete.",
        "noStoreNearby": "{name} (sin tienda cercana): {price}",
        "perChain": (
            "El precio con tarjeta lo fija cada cadena (Walmart: por estado), así que elija "
            "la cadena, no la dirección."
        ),
        "noStock": "No vemos el inventario: llame a la farmacia antes de ir.",
        "restrictedPrices": "Para este medicamento, FineRx muestra solo los precios con tarjeta y la tarjeta.",
        "pharmaciesNear": "Farmacias cerca de {place}",
        "pharmaciesNearby": "Farmacias cercanas",
        "noPlace": "Sin lugar indicado: comparta un código postal de 5 dígitos para ver las farmacias cercanas.",
        "noStoreInRange": "No hay ninguna tienda que podamos ubicar a menos de 30 millas.",
        "storeInStore": "farmacia dentro de la tienda, sin verificar",
        "milesShort": "{n} mi",
        "moreNearby": "… y {n} más cerca.",
        "osm": "Ubicación de las tiendas © colaboradores de OpenStreetMap (ODbL).",
        "zipInvalid": (
            "El código postal debe tener 5 dígitos: envíe un código postal de 5 dígitos para "
            "ver las farmacias cercanas."
        ),
        "rateLimited": "Demasiadas solicitudes en este momento: inténtelo de nuevo en {n} s.",
        "loadFailed": "Los precios no se cargaron. La tarjeta sigue funcionando.",
        "busy": "Los precios están ocupados en este momento: inténtelo de nuevo en breve. La tarjeta sigue funcionando.",
        "drugRequired": "Indique el medicamento (por ejemplo, «atorvastatin 20 mg») para ver los precios con tarjeta.",
        "noMatch": "Ningún medicamento coincide con «{query}». Pruebe search_drugs con otra ortografía.",
        "closeMatches": "Ningún medicamento coincide con «{query}». Coincidencias cercanas: {names}.",
        "zipNotFound": "No conocemos ese código postal. Pruebe con un código postal cercano de 5 dígitos.",
        "freeCard": "Tarjeta gratuita FineRx",
        "cardTitle": "**La tarjeta de descuento gratuita FineRx**: gratis, sin registrarse, no es un seguro.",
        "howToUse": "Cómo usarla:",
        "sayAtCounter": "Diga en el mostrador: «{phrase}»",
        "cardLinks": "Página de la tarjeta: {site} · hoja para imprimir: {print}",
        "cardPriceAt": "{package}: {price} con la tarjeta en {name}, observado el {date}.",
        "noCardPriceFor": "No hay un precio con tarjeta registrado para «{drug}»; la tarjeta funciona igual.",
        "emailSent": "Se envió la tarjeta gratuita FineRx a {to}.",
        "searchHead": "Búsqueda «{query}»: {n} resultado(s).",
        "noCardPriceYet": "aún no se ha visto un precio con tarjeta",
        "fromLine": "con la tarjeta desde {price} para {package}, observado el {date}",
        "foreignBrandLine": (
            "Marca extranjera {brand} ({countries}): principio activo {inn}; llame a find_us_equivalent."
        ),
        "strengthsLine": "Dosis y tamaños de envase con precio con tarjeta: {forms}.",
        "noCardPriceAny": "Aún no se ha visto un precio con tarjeta para ningún paquete de este medicamento.",
        "cardFromLine": "Precio con tarjeta desde {price} para {package}, observado el {date}.",
        "defaultPackage": "Paquete predeterminado {label}: precio con tarjeta por cadena:",
        "havePrescription": "Tiene una receta:",
        "noPrescription": "Aún no tiene receta:",
        "brandCostly": "La marca cuesta demasiado:",
        "noOptions": "No hay opciones registradas.",
        "restrictedRx": (
            "Para este medicamento, FineRx muestra solo los precios con tarjeta y la tarjeta gratuita. "
            "Hable del tratamiento con un profesional de salud autorizado."
        ),
        "usDrugLine": "Medicamento en EE. UU.: {name} (slug {slug}): {price}.",
        "sameBrandElsewhere": "La misma marca en otros países: {list}",
        "noForeignMatch": (
            "Ninguna marca extranjera coincide con «{brand}». Pruebe el principio activo con search_drugs."
        ),
        "brandsAbroad": "Marcas en el extranjero que corresponden a {slug}: {n}.",
        "searchOpened": (
            "Se abrió la búsqueda de FineRx en la tarjeta: la persona escribe un medicamento o una marca "
            "de otro país, lo elige junto con un lugar y ve los precios con tarjeta por cadena."
        ),
        "searchOpenedFor": "Se abrió la búsqueda de FineRx para «{query}» en la tarjeta. Coincidencias:",
        "searchNoMatch": (
            "Aún ningún medicamento coincide con «{query}»; la persona puede precisarlo en el campo de búsqueda."
        ),
        "searchPopular": "Búsquedas frecuentes: {names}.",
        "suggestFrom": "con la tarjeta desde {price}, observado el {date}",
        "foreignSuggest": "Marca extranjera {brand} ({countries}): find_us_equivalent indica qué es en EE. UU.",
        "whereNotFound": (
            "No pudimos ubicar ese lugar: ingrese un código postal de 5 dígitos, o una ciudad con su estado "
            "(por ejemplo, «Austin, TX»)."
        ),
        "rxHave": "Si tiene una receta",
        "rxNone": "Si aún no tiene una",
        "rxBrand": "Si la marca cuesta demasiado",
        "rxCardFrom": "Sin seguro: con la tarjeta desde {price} para {package}, observado el {date}.",
    },
    "ru": {
        "withCardObserved": "{price} с картой, по наблюдению на {date}",
        "zonePrice": "цена для {zone}",
        "placeZip": "{where} (ZIP {zip})",
        "zipOnly": "ZIP {zip}",
        "placeApprox": "{where} (примерно)",
        "yourArea": "ваш район",
        "thisMedicine": "это лекарство",
        "coverageOther": (
            "Цену с картой для {quantity} мы не видели; цены с картой были для таких количеств: "
            "{seen}. Цена никогда не пересчитывается на другое количество."
        ),
        "coverageNone": "Цену с картой для этой упаковки мы пока не видели; финальную цену назовут в аптеке.",
        "pricesNational": (
            "Цена с бесплатной картой FineRx по аптечным сетям по всем США, по возрастанию "
            "(место не указано — по ZIP-коду покажем аптеки рядом):"
        ),
        "pricesNear": "Цена с бесплатной картой FineRx рядом с {place}, по возрастанию:",
        "nearestStore": "ближайший магазин в {miles} милях",
        "noPriceForPackage": "цену с картой для этой упаковки не видели",
        "noPriceShort": "цену с картой не видели",
        "moreChains": "… и ещё {n} сетей в полном списке.",
        "noChain": "Ни у одной аптечной сети нет цены с картой для этой упаковки.",
        "noStoreNearby": "{name} (рядом нет магазина): {price}",
        "perChain": (
            "Цена с картой задаётся для сети целиком (Walmart — по штату), так что выбирайте сеть, "
            "а не адрес."
        ),
        "noStock": "Наличие мы не видим — позвоните в аптеку перед поездкой.",
        "restrictedPrices": "Для этого лекарства FineRx показывает только цены с картой и саму карту.",
        "pharmaciesNear": "Аптеки рядом с {place}",
        "pharmaciesNearby": "Аптеки рядом",
        "noPlace": "Место не указано: сообщите ZIP-код из 5 цифр, чтобы показать аптеки рядом.",
        "noStoreInRange": "В радиусе 30 миль нет магазинов, которые мы можем показать.",
        "storeInStore": "аптека в магазине, не проверено",
        "milesShort": "{n} миль",
        "moreNearby": "… и ещё {n} рядом.",
        "osm": "Адреса магазинов © участники OpenStreetMap (ODbL).",
        "zipInvalid": "ZIP-код должен состоять из 5 цифр — пришлите ZIP из 5 цифр, чтобы увидеть аптеки рядом.",
        "rateLimited": "Сейчас слишком много запросов — повторите через {n} с.",
        "loadFailed": "Цены сейчас не загрузились. Карта всё равно работает.",
        "busy": "Цены сейчас заняты — повторите чуть позже. Карта всё равно работает.",
        "drugRequired": "Назовите лекарство (например, «atorvastatin 20 mg»), чтобы увидеть цены с картой.",
        "noMatch": "Ни одно лекарство не совпало с «{query}». Попробуйте search_drugs с другим написанием.",
        "closeMatches": "Ни одно лекарство не совпало с «{query}». Похожие: {names}.",
        "zipNotFound": "Такой ZIP-код нам неизвестен. Попробуйте соседний ZIP из 5 цифр.",
        "freeCard": "Бесплатная карта FineRx",
        "cardTitle": "**Бесплатная скидочная карта FineRx** — бесплатно, без регистрации, не страховка.",
        "howToUse": "Как пользоваться:",
        "sayAtCounter": "Скажите у кассы: «{phrase}»",
        "cardLinks": "Страница карты: {site} · лист для печати: {print}",
        "cardPriceAt": "{package}: {price} с картой в {name}, по наблюдению на {date}.",
        "noCardPriceFor": "Цены с картой для «{drug}» у нас нет; карта работает так же.",
        "emailSent": "Бесплатная карта FineRx отправлена на {to}.",
        "searchHead": "Поиск «{query}»: совпадений — {n}.",
        "noCardPriceYet": "цену с картой пока не видели",
        "fromLine": "с картой от {price} за {package}, по наблюдению на {date}",
        "foreignBrandLine": (
            "Зарубежный бренд {brand} ({countries}): действующее вещество {inn} — вызовите find_us_equivalent."
        ),
        "strengthsLine": "Дозировки и упаковки с ценой по карте: {forms}.",
        "noCardPriceAny": "Цену с картой пока не видели ни для одной упаковки этого лекарства.",
        "cardFromLine": "Цена с картой от {price} за {package}, по наблюдению на {date}.",
        "defaultPackage": "Упаковка по умолчанию {label} — цена с картой по сетям:",
        "havePrescription": "Рецепт есть:",
        "noPrescription": "Рецепта пока нет:",
        "brandCostly": "Бренд слишком дорогой:",
        "noOptions": "Вариантов нет.",
        "restrictedRx": (
            "Для этого лекарства FineRx показывает только цены с картой и бесплатную карту. "
            "Лечение обсудите с лицензированным врачом."
        ),
        "usDrugLine": "Лекарство в США: {name} (slug {slug}) — {price}.",
        "sameBrandElsewhere": "Тот же бренд в других странах: {list}",
        "noForeignMatch": (
            "Ни один зарубежный бренд не совпал с «{brand}». Попробуйте действующее вещество через search_drugs."
        ),
        "brandsAbroad": "Зарубежные бренды, соответствующие {slug}: {n}.",
        "searchOpened": (
            "В карточке открыт поиск FineRx: человек вводит лекарство или бренд из другой страны, "
            "выбирает его и место и видит цены с картой по сетям."
        ),
        "searchOpenedFor": "В карточке открыт поиск FineRx по «{query}». Совпадения:",
        "searchNoMatch": "Пока ни одно лекарство не совпало с «{query}» — человек может уточнить запрос в поле поиска.",
        "searchPopular": "Часто ищут: {names}.",
        "suggestFrom": "с картой от {price}, по наблюдению на {date}",
        "foreignSuggest": "Зарубежный бренд {brand} ({countries}) — find_us_equivalent скажет, что это в США.",
        "whereNotFound": (
            "Не удалось определить это место — введите ZIP-код из 5 цифр или город со штатом "
            "(например, «Austin, TX»)."
        ),
        "rxHave": "Если рецепт есть",
        "rxNone": "Если рецепта пока нет",
        "rxBrand": "Если бренд слишком дорогой",
        "rxCardFrom": "Без страховки: с картой от {price} за {package}, по наблюдению на {date}.",
    },
}


def _plain(label: str) -> str:
    """"pharmacy in store (not verified)" → "pharmacy in store, not verified" —
    the content wraps it in parentheses itself."""
    return re.sub(r"\s*[(（]\s*(.*?)\s*[)）]\s*$", r", \1", label)


def _borrowed(locale: str) -> dict[str, str]:
    """Content phrases the widget labels already carry in ``locale``."""
    w = _T.get(locale)
    if not w:
        return {}
    return {
        "withCardObserved": "{price} " + w["withCard"] + ", " + w["observed"],
        "noStock": w["noStock"],
        "storeInStore": _plain(w["storeInStore"]),
        "pharmaciesNearby": w["pharmaciesTitle"],
        "milesShort": w["miles"],
        "noPriceShort": w["noPriceShort"],
        "zipInvalid": w["zipInvalid"] + ".",
    }


@functools.lru_cache(maxsize=16)
def text_for(locale: str) -> dict[str, str]:
    """Every content phrase, in ``locale`` where we have it, English otherwise.
    Treat the answer as read-only (it is cached)."""
    return {**TEXT_EN, **_borrowed(locale), **_TEXT.get(locale, {})}


def tr(locale: str, key: str, **values: object) -> str:
    """One content phrase with its ``{placeholders}`` filled."""
    out = text_for(locale if isinstance(locale, str) else "en")[key]
    for name, value in values.items():
        out = out.replace("{" + name + "}", str(value))
    return out
